Задача create-app
js-tasks-ru/vue-20241213_wowsofunny pull request #2
Opened 2024-12-18 18:50 UTC by pavelvorobev

2024-12-18 18:50 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-12-19 21:00 UTC, ShGKme requested changes

2024-12-19 21:00 UTC, ShGKme commented on 01-basics/10-create-app/script.js
> +  template: `<div>Сегодня {{ new Date().toLocaleDateString('en-EN', {dateStyle: 'long'}) }}</div>`,
Вместо фиксированной локализации (`en-US`) лучше всегда использовать `navigator.language`. Так локализация всегда будет той, что пользователь выбрал в настройках своего браузера.

В этой задаче также требуется использовать выбранную пользователем локализацию. 

Сделать это прямо в шаблоне - не получится, так как переменной `navigator` нет в области видимости шаблона. Потребуется добавить `setup`.

2024-12-20 07:43 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-12-20 20:09 UTC, ShGKme approved these changes

2024-12-20 20:09 UTC, merged